updates for oprsite (EL7, modern WDK build)

diff --git a/bin/oprsite b/bin/oprsite
--- a/bin/oprsite
+++ b/bin/oprsite
@@ -24,29 +24,27 @@ readonly SOURCE_WEBSITE=$1
 
 (write_env_dot_file "$SOURCE_WEBSITE" "$CFG_VMENV_FILE")
 
-source $CFG_VMENV_FILE 2>/dev/null || { stat=$?; echo "FATAL: ${CFG_VMENV_FILE} profile appears invalid."; exit $stat; }
+source $CFG_VMENV_FILE 2>/dev/null || { stat=$?; echo "FATAL: ${CFG_VMENV_FILE} propfile appears invalid."; exit $stat; }
 
-sudo sed -i "/127.0.0.1 ${HOST}/d" /etc/hosts || errexit
-sudo /bin/sh -c "echo '127.0.0.1 ${HOST}' >> /etc/hosts" || errexit
-sudo sed -i "s|HOSTNAME=.*|HOSTNAME=${HOST}|" /etc/sysconfig/network  || errexit
-sudo hostname $HOST  || errexit
+sudo sed -i "/127.0.0.1 ${HOST}/d" /etc/hosts || errexit "Could not delete ${HOST} from /etc/hosts"
+sudo /bin/sh -c "echo '127.0.0.1 ${HOST}' >> /etc/hosts" || errexit "Could not add ${HOST} to /etc/hosts"
+# EL6
+#sudo sed -i "s|HOSTNAME=.*|HOSTNAME=${HOST}|" /etc/sysconfig/network  || errexit
+#sudo hostname $HOST  || errexit
+sudo hostnamectl set-hostname $HOST --static || errexit "Could not set hostname to $HOST"
 
 sudo rm -rf "/var/www/${PRODUCT}/${WEBAPP}"
 
 sudo mkdir -p "/var/www/${PRODUCT}"
 sudo chmod 0777 "/var/www/${PRODUCT}"
 
-if ! rpm -q "tomcat-instance-${PRODUCT}" >/dev/null; then
-  sudo yum clean all
-  sudo yum install -y "tomcat-instance-${PRODUCT}"
-  sudo /bin/cp "${ORACLE_HOME}/jdbc/lib/ojdbc6.jar" "/usr/local/tomcat_instances/${PRODUCT}/shared/lib/"
-  sudo instance_manager start $PRODUCT
-fi
+sudo instance_manager enable $PRODUCT || errexit "could not enable $PRODUCT tomcat instance"
+sudo instance_manager start $PRODUCT || errexit "could not start $PRODUCT tomcat instance"
 
 cd ~
 rm -f installWdkSite*.prop
 set +e; echo y | installWdkSite >/dev/null 2>&1; set -e;
-iws-proper installWdkSite_*.prop "$HOST/$WEBAPP"
+OWNER=joeuser iws-proper installWdkSite_*.prop $HOST ${WEBAPP#*.} www
 
 echo y | installWdkSite installWdkSite_*.prop
 
@@ -59,33 +57,16 @@ export RELEASE_NUMBER=$RELEASE_NUMBER
 export BUILD_NUMBER=$BUILD_NUMBER
 EOF
 
-grep -q removePassword /etc/httpd/conf/enabled_sites/$HOST.conf || \
-  sudo sed -i "s:</VirtualHost>:<Perl>\n  require 'conf/lib/Publish.pm';\n  removePassword();\n</Perl>\n\n</VirtualHost>:" /etc/httpd/conf/enabled_sites/$HOST.conf
+#grep -q removePassword /etc/httpd/conf/enabled_sites/$HOST.conf || \
+#  sudo sed -i "s:</VirtualHost>:<Perl>\n  require 'conf/lib/Publish.pm';\n  removePassword();\n</Perl>\n\n</VirtualHost>:" /etc/httpd/conf/enabled_sites/$HOST.conf
 
-sudo service httpd reload || errexit
+sudo systemctl reload httpd || errexit "Could not reload httpd service"
 
-
-sudo -u joeuser /bin/sh -c "cat > ~/.euparc" <<EOF
-<?xml version="1.0" encoding="utf-8"?>
-<euparc>
-  <database>
-    <user login='${CFG_WDK_USER_LOGIN}' password='${CFG_WDK_USER_PASSWORD}' />
-  </database>
-  <oauth>
-    <client clientId='apicomponentsite' clientSecret='${CFG_OAUTH_CLIENT_SECRET}' />
-  </oauth>
-</euparc>
-EOF
-
-
-
-sudo -u joeuser /bin/sh -c "cat > '/var/www/${PRODUCT}/${WEBAPP}/etc/master_configuration_set'" <<EOF
-$HOST appdb  userdb ${CFG_WDK_USER_LOGIN}  ${CFG_WDK_USER_LOGIN}
-EOF
+sudo -u joeuser /bin/sh -c "cp '${OPR_HOME}/conf/conifer_site_vars.yml' '/var/www/${PRODUCT}/${WEBAPP}/etc/conifer_site_vars.yml'"
 
 sudo su - joeuser <<EOF
 source "/var/www/${PRODUCT}/${WEBAPP}/etc/setenv"
 cd \$PROJECT_HOME
 curl -sL "http://${SOURCE_WEBSITE}/dashboard/xml/svn/checkout/value" | /bin/sh
-rebuilder $HOST --use-configula --non-interactive --skip-svn-update
+rebuilder $HOST --use-conifer --non-interactive --skip-svn-update
 EOF
